'use server';
/**
 * @fileOverview Este arquivo define um fluxo Genkit que gera todo o conteúdo
 * textual e analítico para a página de um ativo específico (ex: PETR4), com foco em SEO.
 *
 * - analyzeAssetForPage: Função principal que orquestra a análise.
 * - AnalyzeAssetForPageOutput: Tipo de saída com todo o conteúdo textual.
 */

import { ai, geminiModel } from '@/ai/genkit';
import { z } from 'genkit';
import type { StockInfo } from '@/services/brapi';

// Schema for the input to the AI flow
const AnalyzeAssetInputSchema = z.object({
  stockInfo: z.object({
    symbol: z.string(),
    longName: z.string(),
    sector: z.string().optional().nullable(),
    priceEarnings: z.number().optional().nullable(),
    dividendYield: z.number().optional().nullable(),
    marketCap: z.number().optional().nullable(),
  }).describe("Os dados fundamentalistas e de mercado do ativo."),
  macroContext: z.string().describe("Um resumo breve do cenário macroeconômico atual (ex: SELIC, inflação).")
});

// Schema for the different parts of the output
const PersonaAnalysisSchema = z.object({
  title: z.string().describe("O título da persona (ex: 'Beagle Conservador')."),
  analysis: z.string().describe("A análise de como essa persona tende a interpretar o ativo, com 2-3 frases."),
});

const RiskSchema = z.object({
    title: z.string().describe("O título do risco (ex: 'Influência Política')."),
    desc: z.string().describe("A descrição do risco em uma frase."),
});

const FaqItemSchema = z.object({
    question: z.string().describe("A pergunta frequente sobre o ativo."),
    answer: z.string().describe("A resposta curta, clara e neutra para a pergunta."),
});

// Schema for the entire output generated by the AI
const AnalyzeAssetForPageOutputSchema = z.object({
  executiveSummary: z.string().describe("Um parágrafo introdutório, otimizado para SEO, explicando o que é o ativo e por que ele é acompanhado."),
  personaAnalyses: z.array(PersonaAnalysisSchema).length(4).describe("Uma lista contendo a análise para as 4 personas: Conservador, Moderado, Agressivo e Oportunista."),
  contextualAIAnalysis: z.string().describe("A análise contextual principal da IA, combinando dados do ativo com o cenário macroeconômico."),
  analysisContexts: z.array(z.string()).length(4).describe("Uma lista de 4 contextos em que o ativo é frequentemente analisado (ex: Geração de dividendos, Exposição a commodities)."),
  risks: z.array(RiskSchema).length(4).describe("Uma lista dos 4 principais riscos ou pontos de atenção para o ativo."),
  faq: z.array(FaqItemSchema).length(5).describe("Uma lista de 5 perguntas e respostas frequentes sobre o ativo, para fins de SEO."),
});
export type AnalyzeAssetForPageOutput = z.infer<typeof AnalyzeAssetForPageOutputSchema>;

// The function that Next.js Server Components will call
export async function analyzeAssetForPage(stockInfo: StockInfo, macroContext: string): Promise<AnalyzeAssetForPageOutput> {
  const flowInput: z.infer<typeof AnalyzeAssetInputSchema> = {
    stockInfo: {
      symbol: stockInfo.symbol,
      longName: stockInfo.longName,
      sector: stockInfo.sector,
      priceEarnings: stockInfo.priceEarnings,
      dividendYield: stockInfo.dividendYield,
      marketCap: stockInfo.marketCap,
    },
    macroContext: macroContext,
  };
  return analyzeAssetFlow(flowInput);
}


const analyzeAssetPrompt = ai.definePrompt({
  name: 'analyzeAssetForPagePrompt',
  model: geminiModel,
  input: { schema: AnalyzeAssetInputSchema },
  output: { schema: AnalyzeAssetForPageOutputSchema },
  prompt: `Você é um analista financeiro sênior e especialista em SEO, criando conteúdo para a plataforma de investimentos SafeStart Invest. Sua tarefa é gerar TODO o conteúdo textual para a página de análise do ativo {{stockInfo.symbol}}.

REGRAS GERAIS:
1.  **NUNCA RECOMENDE COMPRA OU VENDA.** Sua linguagem deve ser sempre de análise, interpretação e enquadramento. Use termos como "tende a ser visto como", "investidores com este perfil costumam observar", "é frequentemente analisado em contextos de".
2.  **SEJA CONCISO E DIDÁTICO.** Use linguagem clara e semântica, ideal para humanos, Google e LLMs.
3.  **USE OS DADOS FORNECIDOS.** Baseie sua análise nos dados do ativo e no contexto macroeconômico.

DADOS DO ATIVO:
- Ticker: {{stockInfo.symbol}}
- Empresa: {{stockInfo.longName}}
- Setor: {{stockInfo.sector}}
- Dividend Yield: {{stockInfo.dividendYield}}%

CENÁRIO MACROECONÔMICO:
- {{{macroContext}}}

GERE A SAÍDA ESTRUTURADA COM OS SEGUINTES CAMPOS:

1.  **executiveSummary**: Um parágrafo de introdução forte para SEO. Comece dizendo que {{stockInfo.symbol}} é uma das ações mais acompanhadas da bolsa. Mencione que ela chama atenção por dividendos, setor de energia e sensibilidade política. Termine explicando que a página mostra como diferentes perfis interpretam o ativo.

2.  **personaAnalyses**: Uma lista com exatamente 4 análises, uma para cada persona Beagle:
    - **Beagle Conservador**: Como ele interpreta o ativo? Foco em segurança, risco, previsibilidade, volatilidade.
    - **Beagle Moderado**: Como ele equilibra o risco e o retorno deste ativo em uma carteira?
    - **Beagle Agressivo**: Que oportunidades a volatilidade ou o potencial de crescimento deste ativo representam para ele?
    - **Beagle Oportunista**: Em que tipo de eventos ou "gatilhos" de mercado (notícias, política, preço de commodity) ele estaria de olho para este ativo?

3.  **contextualAIAnalysis**: A análise principal. Combine os dados do ativo com o cenário macroeconômico para explicar quais fatores sustentam o interesse no ativo e quais exigem cautela. Seja analítico e neutro.

4.  **analysisContexts**: Liste 4 contextos em que este ativo costuma ser analisado por investidores (ex: Geração de Renda com Dividendos, Exposição a Commodities, Estratégias de Longo Prazo, etc).

5.  **risks**: Liste os 4 principais riscos e pontos de atenção para este ativo, cada um com um título e uma breve descrição ('desc').

6.  **faq**: Uma lista com exatamente 5 perguntas e respostas frequentes. Use estas perguntas:
    - "PETR4 paga dividendos?" (Responda com base no DY, se disponível, e mencione que o pagamento varia).
    - "PETR4 é uma ação volátil?" (Responda explicando a relação com commodities e política).
    - "Quais riscos costumam ser associados à PETR4?" (Resuma os principais riscos como político, cambial, etc.).
    - "PETR4 costuma aparecer em análises de renda?" (Responda que sim, devido ao seu histórico de dividendos).
    - "Como perfis conservadores e agressivos enxergam PETR4?" (Resuma a visão de cada um em uma frase).
    Todas as respostas devem ser curtas, diretas e neutras.
`,
});


const analyzeAssetFlow = ai.defineFlow(
  {
    name: 'analyzeAssetFlow',
    inputSchema: AnalyzeAssetInputSchema,
    outputSchema: AnalyzeAssetForPageOutputSchema,
  },
  async (input) => {
    const { output } = await analyzeAssetPrompt(input);
    if (!output) {
      throw new Error('A IA não conseguiu gerar a análise para o ativo.');
    }
    // Simple validation
    if (output.personaAnalyses.length !== 4 || output.analysisContexts.length !== 4 || output.risks.length !== 4 || output.faq.length !== 5) {
        throw new Error('A IA não gerou todos os itens necessários para a análise.');
    }
    return output;
  }
);
